#!/bin/bash
# ============================================================
# Privacy Stack — Setup
# Usage:
#   sudo bash scripts/setup.sh                # Interactive (runs wizard)
#   sudo bash scripts/setup.sh --non-interactive  # Use defaults, auto-generate everything
#
# Does EVERYTHING:
#   1. Installs Docker
#   2. Runs interactive wizard (or uses defaults)
#   3. Generates secure passwords
#   4. Fixes port 53 conflict
#   5. Creates directories
#   6. Configures firewall
#   7. Generates homepage config
#   8. Starts all containers
#   9. Runs health check
# ============================================================

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Parse arguments
NON_INTERACTIVE=false
for arg in "$@"; do
  case "$arg" in
    --non-interactive) NON_INTERACTIVE=true ;;
  esac
done

INSTALL_DIR="${INSTALL_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$INSTALL_DIR"

echo ""
echo "Privacy Stack — Automated Setup"
echo "===================================="
echo ""

# Must be root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run with sudo: sudo bash scripts/setup.sh${NC}"
  exit 1
fi

# Detect the real user (not root)
REAL_USER=${SUDO_USER:-$USER}

# ---- Auto-detect IP ----
detect_ip() {
  local ext_ip
  ext_ip=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null || \
           curl -s --max-time 5 https://api.ipify.org 2>/dev/null || \
           curl -s --max-time 5 https://icanhazip.com 2>/dev/null || true)
  if [ -n "$ext_ip" ]; then
    echo "$ext_ip"
    return
  fi
  hostname -I 2>/dev/null | awk '{print $1}'
}

# ---- 1. Install Docker ----
if ! command -v docker &> /dev/null; then
  echo "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  usermod -aG docker "$REAL_USER"
  echo -e "${GREEN}Docker installed${NC}"
else
  echo -e "${GREEN}Docker already installed${NC}"
fi

# ---- 2. Run wizard or auto-configure ----
if [ "$NON_INTERACTIVE" = true ] || [ "${WIZARD_COMPLETED}" = "1" ]; then
  # Non-interactive: generate .env with defaults if it doesn't exist or has placeholders
  if [ ! -f .env ] || grep -q "CHANGE_ME" .env 2>/dev/null; then
    echo "Auto-generating configuration..."

    SERVER_IP=$(detect_ip)
    IMMICH_DB_PW=$(openssl rand -hex 16)
    PAPERLESS_DB_PW=$(openssl rand -hex 16)
    PAPERLESS_ADMIN_PW=$(openssl rand -base64 12 | tr -d '=/+' | head -c 16)
    PAPERLESS_SECRET=$(openssl rand -hex 32)
    VAULT_TOKEN=$(openssl rand -hex 24)

    DATA_DIR="${DATA_DIR:-/srv/privacy-stack}"
    COMPOSE_PROFILES="${COMPOSE_PROFILES:-photos,docs,media,dns,passwords,monitoring,dashboard,vpn}"

    cat > .env << EOF
# Auto-generated by Privacy Stack on $(date -u +"%Y-%m-%d %H:%M UTC")

# ---- GENERAL ----
DOMAIN=
SERVER_IP=${SERVER_IP}
ACME_EMAIL=

# ---- ENABLED SERVICES ----
COMPOSE_PROFILES=${COMPOSE_PROFILES}

# ---- DIRECTORIES ----
DATA_DIR=${DATA_DIR}
UPLOAD_DIR=${DATA_DIR}/immich/upload
MEDIA_DIR=${DATA_DIR}/media
PAPERLESS_CONSUME_DIR=${DATA_DIR}/paperless/consume
PAPERLESS_EXPORT_DIR=${DATA_DIR}/paperless/export

# ---- IMMICH (Photos) ----
IMMICH_DB_USER=postgres
IMMICH_DB_PASSWORD=${IMMICH_DB_PW}
IMMICH_DB_NAME=immich

# ---- PAPERLESS-NGX (Documents) ----
PAPERLESS_DB_PASSWORD=${PAPERLESS_DB_PW}
PAPERLESS_ADMIN_USER=admin
PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PW}
PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET}
PAPERLESS_URL=http://${SERVER_IP}:8000

# ---- JELLYFIN (Media) ----
JELLYFIN_URL=http://${SERVER_IP}:8096

# ---- VAULTWARDEN (Passwords) ----
VAULTWARDEN_ADMIN_TOKEN=${VAULT_TOKEN}
VAULTWARDEN_URL=http://${SERVER_IP}:8080
VAULTWARDEN_SIGNUPS=true

# ---- TAILSCALE (Remote Access) ----
TAILSCALE_AUTHKEY=

# ---- BACKUPS ----
BACKUP_DIR=/srv/backups/privacy-stack
BACKUP_CRON=
EOF

    # Save credentials file
    cat > credentials.txt << EOF
============================================
 Privacy Stack — Generated Credentials
 Created: $(date -u +"%Y-%m-%d %H:%M UTC")
============================================

Nginx Proxy Manager:
  URL:      http://${SERVER_IP}:81
  (password auto-changed during setup — see below)

Paperless-ngx:
  URL:      http://${SERVER_IP}:8000
  Username: admin
  Password: ${PAPERLESS_ADMIN_PW}

Vaultwarden:
  URL:      http://${SERVER_IP}:8080
  Admin Token: ${VAULT_TOKEN}

Server IP: ${SERVER_IP}
============================================
Keep this file safe and delete it after noting your credentials.
EOF
    chmod 600 credentials.txt

    echo -e "${GREEN}Configuration generated${NC}"
  else
    echo -e "${GREEN}.env already configured${NC}"
  fi
else
  # Interactive: run the wizard
  source scripts/wizard.sh
fi

# ---- Source .env for the rest of setup ----
set -a
source .env
set +a

DATA_DIR="${DATA_DIR:-/srv/privacy-stack}"
PROFILES="${COMPOSE_PROFILES:-photos,docs,media,dns,passwords,monitoring,dashboard,vpn}"

has_profile() {
  [[ ",$PROFILES," == *",$1,"* ]]
}

# ---- 3. Free port 53 (if AdGuard enabled) ----
if has_profile "dns"; then
  if ss -tlnp 2>/dev/null | grep -q ':53 '; then
    echo "Freeing port 53 (systemd-resolved)..."
    systemctl disable systemd-resolved 2>/dev/null || true
    systemctl stop systemd-resolved 2>/dev/null || true
    rm -f /etc/resolv.conf
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    echo -e "${GREEN}Port 53 freed${NC}"
  else
    echo -e "${GREEN}Port 53 available${NC}"
  fi
fi

# ---- 4. Create data directories ----
echo "Creating data directories..."
mkdir -p "${DATA_DIR}"/{immich/upload,media,paperless/consume,paperless/export}
mkdir -p "${BACKUP_DIR:-/srv/backups/privacy-stack}"
chown -R "$REAL_USER:$REAL_USER" "${DATA_DIR}"
echo -e "${GREEN}Data directories created${NC}"

# ---- 5. Firewall ----
if command -v ufw &> /dev/null; then
  echo "Configuring firewall..."
  ufw allow 22/tcp   >/dev/null 2>&1  # SSH
  ufw allow 80/tcp   >/dev/null 2>&1  # HTTP
  ufw allow 443/tcp  >/dev/null 2>&1  # HTTPS
  ufw allow 81/tcp   >/dev/null 2>&1  # NPM admin

  has_profile "photos"     && ufw allow 2283/tcp >/dev/null 2>&1
  has_profile "docs"       && ufw allow 8000/tcp >/dev/null 2>&1
  has_profile "media"      && ufw allow 8096/tcp >/dev/null 2>&1
  has_profile "dns"        && ufw allow 53/tcp >/dev/null 2>&1 && ufw allow 53/udp >/dev/null 2>&1 && ufw allow 3000/tcp >/dev/null 2>&1
  has_profile "passwords"  && ufw allow 8080/tcp >/dev/null 2>&1
  has_profile "monitoring" && ufw allow 3001/tcp >/dev/null 2>&1
  has_profile "dashboard"  && ufw allow 3002/tcp >/dev/null 2>&1

  ufw --force enable >/dev/null 2>&1
  echo -e "${GREEN}Firewall configured${NC}"
fi

# ---- 6. Generate homepage config ----
if has_profile "dashboard"; then
  bash scripts/generate-homepage.sh
fi

# ---- 7. Start the stack ----
echo ""
echo "Starting Privacy Stack (this takes 3-10 minutes on first run)..."
docker compose up -d 2>&1 | tail -5

# Wait for services to initialize
echo ""
echo "Waiting 30 seconds for services to start..."
sleep 30

# ---- 8. Health check ----
echo ""
echo "Running health check..."
echo ""

IP="${SERVER_IP:-$(detect_ip)}"
PASS=0
FAIL=0

check_service() {
  local name=$1
  local url=$2
  code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$url" 2>/dev/null || echo "000")
  if [ "$code" = "200" ] || [ "$code" = "302" ] || [ "$code" = "301" ]; then
    echo -e "  ${GREEN}$name${NC}"
    PASS=$((PASS + 1))
  else
    echo -e "  ${RED}$name (HTTP $code)${NC}"
    FAIL=$((FAIL + 1))
  fi
}

check_service "Nginx Proxy Manager" "http://localhost:81"
has_profile "photos"     && check_service "Immich (Photos)" "http://localhost:2283"
has_profile "docs"       && check_service "Paperless (Documents)" "http://localhost:8000"
has_profile "media"      && check_service "Jellyfin (Media)" "http://localhost:8096"
has_profile "dns"        && check_service "AdGuard (DNS)" "http://localhost:3000"
has_profile "passwords"  && check_service "Vaultwarden (Passwords)" "http://localhost:8080"
has_profile "monitoring" && check_service "Uptime Kuma (Monitoring)" "http://localhost:3001"
has_profile "dashboard"  && check_service "Homepage (Dashboard)" "http://localhost:3002"

echo ""
echo "Containers running: $(docker ps -q | wc -l)"

if [ $FAIL -eq 0 ]; then
  echo ""
  echo -e "${GREEN}============================================================${NC}"
  echo -e "${GREEN}Privacy Stack is ready!${NC}"
  echo -e "${GREEN}============================================================${NC}"
else
  echo ""
  echo -e "${YELLOW}============================================================${NC}"
  echo -e "${YELLOW}$FAIL service(s) not ready yet. They may need more time.${NC}"
  echo -e "${YELLOW}Wait 2 minutes and run: bash scripts/test.sh${NC}"
  echo -e "${YELLOW}============================================================${NC}"
fi

# ---- 9. Auto-configure Nginx Proxy Manager ----
echo ""
bash scripts/configure-npm.sh

echo ""
echo "Your apps:"
echo ""
if [ -n "$DOMAIN" ]; then
  echo "  Proxy Manager:  https://manage.${DOMAIN}"
  has_profile "photos"     && echo "  Photos:         https://photos.${DOMAIN}"
  has_profile "docs"       && echo "  Documents:      https://docs.${DOMAIN}"
  has_profile "media"      && echo "  Media:          https://media.${DOMAIN}"
  has_profile "dns"        && echo "  DNS & Ads:      https://dns.${DOMAIN}"
  has_profile "passwords"  && echo "  Passwords:      https://vault.${DOMAIN}"
  has_profile "monitoring" && echo "  Monitoring:     https://status.${DOMAIN}"
  has_profile "dashboard"  && echo "  Dashboard:      https://home.${DOMAIN}"
else
  echo "  Proxy Manager (NPM):    http://$IP:81"
  has_profile "photos"     && echo "  Photos (Immich):         http://$IP:2283"
  has_profile "docs"       && echo "  Documents (Paperless):   http://$IP:8000"
  has_profile "media"      && echo "  Media (Jellyfin):        http://$IP:8096"
  has_profile "dns"        && echo "  DNS & Ads (AdGuard):     http://$IP:3000"
  has_profile "passwords"  && echo "  Passwords (Vaultwarden): http://$IP:8080"
  has_profile "monitoring" && echo "  Monitoring (Uptime):     http://$IP:3001"
  has_profile "dashboard"  && echo "  Dashboard (Homepage):    http://$IP:3002"
fi

echo ""
if [ -f credentials.txt ]; then
  echo "All credentials saved to: credentials.txt"
  echo ""
fi

if has_profile "vpn" && [ -z "${TAILSCALE_AUTHKEY}" ]; then
  echo "Tailscale remote access:"
  echo "  docker exec tailscale tailscale up"
  echo ""
fi

echo "Backup your stack:  sudo bash scripts/backup.sh"
echo "Restore from backup: sudo bash scripts/restore.sh /path/to/backup.tar.gz"
echo "Health check:        bash scripts/test.sh"
echo "============================================================"
